# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculate_checksum.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogCalculateChecksum(object):
    def setupUi(self, DialogCalculateChecksum):
        DialogCalculateChecksum.setObjectName("DialogCalculateChecksum")
        DialogCalculateChecksum.resize(448, 448)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DialogCalculateChecksum.sizePolicy().hasHeightForWidth())
        DialogCalculateChecksum.setSizePolicy(sizePolicy)
        DialogCalculateChecksum.setMinimumSize(QtCore.QSize(448, 448))
        DialogCalculateChecksum.setMaximumSize(QtCore.QSize(448, 448))
        DialogCalculateChecksum.setBaseSize(QtCore.QSize(448, 448))
        DialogCalculateChecksum.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogCalculateChecksum)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelSaveChecksumFileTo = QtWidgets.QLabel(DialogCalculateChecksum)
        self.labelSaveChecksumFileTo.setObjectName("labelSaveChecksumFileTo")
        self.verticalLayout_2.addWidget(self.labelSaveChecksumFileTo)
        self.lineEditSaveChecksumFileTo = QtWidgets.QLineEdit(DialogCalculateChecksum)
        self.lineEditSaveChecksumFileTo.setObjectName("lineEditSaveChecksumFileTo")
        self.verticalLayout_2.addWidget(self.lineEditSaveChecksumFileTo)
        self.checkBoxCreateSeparateChecksumFile = QtWidgets.QCheckBox(DialogCalculateChecksum)
        self.checkBoxCreateSeparateChecksumFile.setObjectName("checkBoxCreateSeparateChecksumFile")
        self.verticalLayout_2.addWidget(self.checkBoxCreateSeparateChecksumFile)
        self.checkBoxOpenChecksumFile = QtWidgets.QCheckBox(DialogCalculateChecksum)
        self.checkBoxOpenChecksumFile.setObjectName("checkBoxOpenChecksumFile")
        self.verticalLayout_2.addWidget(self.checkBoxOpenChecksumFile)
        self.scrollAreaCheckSum = QtWidgets.QScrollArea(DialogCalculateChecksum)
        self.scrollAreaCheckSum.setWidgetResizable(True)
        self.scrollAreaCheckSum.setObjectName("scrollAreaCheckSum")
        self.scrollAreaWidgetContentsCheckSum = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsCheckSum.setGeometry(QtCore.QRect(0, 0, 424, 281))
        self.scrollAreaWidgetContentsCheckSum.setObjectName("scrollAreaWidgetContentsCheckSum")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContentsCheckSum)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowserCheckSum = QtWidgets.QTextBrowser(self.scrollAreaWidgetContentsCheckSum)
        self.textBrowserCheckSum.setObjectName("textBrowserCheckSum")
        self.verticalLayout.addWidget(self.textBrowserCheckSum)
        self.scrollAreaCheckSum.setWidget(self.scrollAreaWidgetContentsCheckSum)
        self.verticalLayout_2.addWidget(self.scrollAreaCheckSum)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogCalculateChecksum)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.labelSaveChecksumFileTo.setBuddy(self.lineEditSaveChecksumFileTo)

        self.retranslateUi(DialogCalculateChecksum)
        self.buttonBox.accepted.connect(DialogCalculateChecksum.accept) # type: ignore
        self.buttonBox.rejected.connect(DialogCalculateChecksum.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DialogCalculateChecksum)

    def retranslateUi(self, DialogCalculateChecksum):
        _translate = QtCore.QCoreApplication.translate
        DialogCalculateChecksum.setWindowTitle(_translate("DialogCalculateChecksum", "Calculate checksum..."))
        self.labelSaveChecksumFileTo.setText(_translate("DialogCalculateChecksum", "Save checksum file(s) to:"))
        self.checkBoxCreateSeparateChecksumFile.setText(_translate("DialogCalculateChecksum", "Create separate checksum file for each file"))
        self.checkBoxOpenChecksumFile.setText(_translate("DialogCalculateChecksum", "Open checksum file after job is completed"))
