# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_symbolic_link.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CreateSymbolicLink(object):
    def setupUi(self, CreateSymbolicLink):
        CreateSymbolicLink.setObjectName("CreateSymbolicLink")
        CreateSymbolicLink.setWindowModality(QtCore.Qt.WindowModal)
        CreateSymbolicLink.resize(512, 256)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CreateSymbolicLink.sizePolicy().hasHeightForWidth())
        CreateSymbolicLink.setSizePolicy(sizePolicy)
        CreateSymbolicLink.setMinimumSize(QtCore.QSize(512, 254))
        CreateSymbolicLink.setMaximumSize(QtCore.QSize(512, 256))
        CreateSymbolicLink.setBaseSize(QtCore.QSize(512, 256))
        CreateSymbolicLink.setSizeGripEnabled(False)
        CreateSymbolicLink.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(CreateSymbolicLink)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lineEditDestination = QtWidgets.QLineEdit(CreateSymbolicLink)
        self.lineEditDestination.setObjectName("lineEditDestination")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditDestination)
        self.lineEditLinkName = QtWidgets.QLineEdit(CreateSymbolicLink)
        self.lineEditLinkName.setObjectName("lineEditLinkName")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditLinkName)
        self.labelDestination = QtWidgets.QLabel(CreateSymbolicLink)
        self.labelDestination.setObjectName("labelDestination")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.labelDestination)
        self.labelLinkName = QtWidgets.QLabel(CreateSymbolicLink)
        self.labelLinkName.setObjectName("labelLinkName")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelLinkName)
        self.checkBoxRelativePath = QtWidgets.QCheckBox(CreateSymbolicLink)
        self.checkBoxRelativePath.setObjectName("checkBoxRelativePath")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.checkBoxRelativePath)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(CreateSymbolicLink)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.labelDestination.setBuddy(self.lineEditDestination)
        self.labelLinkName.setBuddy(self.lineEditLinkName)

        self.retranslateUi(CreateSymbolicLink)
        self.buttonBox.accepted.connect(CreateSymbolicLink.accept) # type: ignore
        self.buttonBox.rejected.connect(CreateSymbolicLink.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CreateSymbolicLink)
        CreateSymbolicLink.setTabOrder(self.lineEditDestination, self.lineEditLinkName)
        CreateSymbolicLink.setTabOrder(self.lineEditLinkName, self.checkBoxRelativePath)

    def retranslateUi(self, CreateSymbolicLink):
        _translate = QtCore.QCoreApplication.translate
        CreateSymbolicLink.setWindowTitle(_translate("CreateSymbolicLink", "Create symbolic link"))
        self.labelDestination.setText(_translate("CreateSymbolicLink", "Destination that the link will point to"))
        self.labelLinkName.setText(_translate("CreateSymbolicLink", "Link name"))
        self.checkBoxRelativePath.setText(_translate("CreateSymbolicLink", "Use relative path when possible"))
