# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(959, 292)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(12, 12, 551, 34))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonLeft = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(5)
        sizePolicy.setHeightForWidth(self.pushButtonLeft.sizePolicy().hasHeightForWidth())
        self.pushButtonLeft.setSizePolicy(sizePolicy)
        self.pushButtonLeft.setMinimumSize(QtCore.QSize(64, 32))
        self.pushButtonLeft.setBaseSize(QtCore.QSize(64, 32))
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.horizontalLayout.addWidget(self.pushButtonLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonStar = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonStar.sizePolicy().hasHeightForWidth())
        self.pushButtonStar.setSizePolicy(sizePolicy)
        self.pushButtonStar.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonStar.setBaseSize(QtCore.QSize(32, 32))
        self.pushButtonStar.setObjectName("pushButtonStar")
        self.horizontalLayout.addWidget(self.pushButtonStar)
        self.pushButtonSlash = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSlash.sizePolicy().hasHeightForWidth())
        self.pushButtonSlash.setSizePolicy(sizePolicy)
        self.pushButtonSlash.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonSlash.setBaseSize(QtCore.QSize(32, 32))
        self.pushButtonSlash.setObjectName("pushButtonSlash")
        self.horizontalLayout.addWidget(self.pushButtonSlash)
        self.pushButtonTwoPoint = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(32)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonTwoPoint.sizePolicy().hasHeightForWidth())
        self.pushButtonTwoPoint.setSizePolicy(sizePolicy)
        self.pushButtonTwoPoint.setMinimumSize(QtCore.QSize(32, 32))
        self.pushButtonTwoPoint.setBaseSize(QtCore.QSize(32, 32))
        self.pushButtonTwoPoint.setObjectName("pushButtonTwoPoint")
        self.horizontalLayout.addWidget(self.pushButtonTwoPoint)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 959, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonLeft.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButtonStar.setText(_translate("MainWindow", "*"))
        self.pushButtonSlash.setText(_translate("MainWindow", "\\"))
        self.pushButtonTwoPoint.setText(_translate("MainWindow", ".."))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
