# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'unpackfiles.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(576, 320)
        Dialog.setMinimumSize(QtCore.QSize(576, 320))
        Dialog.setMaximumSize(QtCore.QSize(576, 320))
        Dialog.setBaseSize(QtCore.QSize(576, 320))
        Dialog.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelExtractFilesMatchingFileMask = QtWidgets.QLabel(Dialog)
        self.labelExtractFilesMatchingFileMask.setObjectName("labelExtractFilesMatchingFileMask")
        self.gridLayout.addWidget(self.labelExtractFilesMatchingFileMask, 0, 0, 1, 1)
        self.comboBoxExtractFilesMatchingFileMask = QtWidgets.QComboBox(Dialog)
        self.comboBoxExtractFilesMatchingFileMask.setEditable(True)
        self.comboBoxExtractFilesMatchingFileMask.setObjectName("comboBoxExtractFilesMatchingFileMask")
        self.comboBoxExtractFilesMatchingFileMask.addItem("")
        self.gridLayout.addWidget(self.comboBoxExtractFilesMatchingFileMask, 0, 1, 1, 1)
        self.labelEditToTheDirectory = QtWidgets.QLabel(Dialog)
        self.labelEditToTheDirectory.setObjectName("labelEditToTheDirectory")
        self.gridLayout.addWidget(self.labelEditToTheDirectory, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditToTheDirectory = QtWidgets.QLineEdit(Dialog)
        self.lineEditToTheDirectory.setObjectName("lineEditToTheDirectory")
        self.horizontalLayout.addWidget(self.lineEditToTheDirectory)
        self.pushButtonOpenDirectory = QtWidgets.QPushButton(Dialog)
        self.pushButtonOpenDirectory.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../pyCommander/pixmaps/dctheme/16x16/actions/cm_switchignorelist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonOpenDirectory.setIcon(icon)
        self.pushButtonOpenDirectory.setObjectName("pushButtonOpenDirectory")
        self.horizontalLayout.addWidget(self.pushButtonOpenDirectory)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.checkBoxUnpackEachArchiveToSeparateSubdir = QtWidgets.QCheckBox(Dialog)
        self.checkBoxUnpackEachArchiveToSeparateSubdir.setObjectName("checkBoxUnpackEachArchiveToSeparateSubdir")
        self.gridLayout.addWidget(self.checkBoxUnpackEachArchiveToSeparateSubdir, 2, 0, 1, 2)
        self.checkBoxUnpackPathNamesIfStoredWithFiles = QtWidgets.QCheckBox(Dialog)
        self.checkBoxUnpackPathNamesIfStoredWithFiles.setChecked(True)
        self.checkBoxUnpackPathNamesIfStoredWithFiles.setObjectName("checkBoxUnpackPathNamesIfStoredWithFiles")
        self.gridLayout.addWidget(self.checkBoxUnpackPathNamesIfStoredWithFiles, 3, 0, 1, 2)
        self.checkBoxOverwriteExistingFiles = QtWidgets.QCheckBox(Dialog)
        self.checkBoxOverwriteExistingFiles.setObjectName("checkBoxOverwriteExistingFiles")
        self.gridLayout.addWidget(self.checkBoxOverwriteExistingFiles, 4, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPassword = QtWidgets.QLabel(Dialog)
        self.labelPassword.setObjectName("labelPassword")
        self.horizontalLayout_2.addWidget(self.labelPassword)
        self.lineEditPassword = QtWidgets.QLineEdit(Dialog)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.horizontalLayout_2.addWidget(self.lineEditPassword)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Unpack files"))
        self.labelExtractFilesMatchingFileMask.setText(_translate("Dialog", "Extract files matching file mask:"))
        self.comboBoxExtractFilesMatchingFileMask.setItemText(0, _translate("Dialog", "*.*"))
        self.labelEditToTheDirectory.setText(_translate("Dialog", "To the directory:"))
        self.checkBoxUnpackEachArchiveToSeparateSubdir.setText(_translate("Dialog", "Unpack each arcive to a separate subdir (name of the archive)"))
        self.checkBoxUnpackPathNamesIfStoredWithFiles.setText(_translate("Dialog", "Unpack path names if stored with files"))
        self.checkBoxOverwriteExistingFiles.setText(_translate("Dialog", "Overwrite existing files"))
        self.labelPassword.setText(_translate("Dialog", "Password for encrypted files:"))
